// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use environment variables for production deployment, with fallbacks for local development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://whnsvkikxqcjzvxwetla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobnN2a2lreHFjanp2eHdldGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjIxNTQsImeXhwIjoyMDY5Mjk4MTU0fQ.-GknuFhhw5PjkrM178uhIDcFxE5exBGJrswDvdxuLGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);