// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://whnsvkikxqcjzvxwetla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobnN2a2lreHFjanp2eHdldGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjIxNTQsImV4cCI6MjA2OTI5ODE1NH0.-GknuFhhw5PjkrM178uhIDcFxE5exBGJrswDvdxuLGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);